# This file was generated by GoReleaser. DO NOT EDIT.
cask "openings-mcp" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a523405c0756d5c0ca6e051842a775bedc8f24f8f33f5bec700524e8f76372d7"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bad0fc9546961f234914ed438951f10b0125f970cdf463b3cea35af0ec70d637"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26a4b27c2673643b3598a9fb2361fd51ba74bc7003611b173878b793b70367ea"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbc145f1b1896efcc4bc9e053cc6a59ce119df0599b140f628962a60951b084e"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_linux_arm64.tar.gz"
    end
  end

  name "openings-mcp"
  desc "MCP server for searching job listings across job boards and company career sites"
  homepage "https://github.com/amikai/openings-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openings-mcp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openings-mcp"] if OS.mac?
  end

  # No zap stanza required

end
