# This file was generated by GoReleaser. DO NOT EDIT.
cask "openings-mcp" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "2abbcf96a7137bfbf69ac17fd442db10ab4ef92437a7cb5e06f4d39e13826fd6"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3242fcb9c6f9075945a30b3b9bbe93c329dcb782edd6476dc9d4bb986b0d7021"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "77987930df2904b63433c7da0fbf768464b1396149f5b9abb8fda270b7a08f9f"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "221f6b699b137a7d0b84fd340fc242162223056b3718b7852e53bd040603fb4e"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_linux_arm64.tar.gz"
    end
  end

  name "openings-mcp"
  desc "MCP server for searching job listings across job boards and company career sites"
  homepage "https://github.com/amikai/openings-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openings-mcp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openings-mcp"] if OS.mac?
  end

  # No zap stanza required

end
