# This file was generated by GoReleaser. DO NOT EDIT.
cask "openings-mcp" do
  version "0.5.4"

  on_macos do
    on_intel do
      sha256 "9d3a3a8c1d1a4e54d11c3445cb5c9dd5a6b04a62c73fd619e2ab0b10659366e1"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "55a88e3be13170e6277e48d0fe3f8a3c2dd2567dc71fbed0aa7b87db4643debe"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c4c7e00b4bca988cffb5c7ff0e805bd506740e6e225fda4043a2cc7ba5b2880"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b066e96c409b02030d54dbd9e841323028ae6d5b2e7c53ec610950782755c043"
      url "https://github.com/amikai/openings-mcp/releases/download/v#{version}/openings-mcp_linux_arm64.tar.gz"
    end
  end

  name "openings-mcp"
  desc "MCP server for searching job listings across job boards and company career sites"
  homepage "https://github.com/amikai/openings-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openings-mcp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openings-mcp"] if OS.mac?
  end

  # No zap stanza required

end
